env: 
  secure: "l+9jKDHkGlztevhwnMg7VI/qIP4LARIBgTzrBYoe13SRe6C0/iFu9MD33LGwadIDu6/JxQ38KxDBFrxO1lIG0LSlq7yjj2BTin5uMdGRIfvVsy5RKxCRm0+EHj9jB/+csJ1VII7PxESPtKicoviIdCyIPF1VXLGP9/TXFkNdqut3V2nL6EUxg7CrtxxQZgLBpxHJr/WTnVQ8c+ZBD86AXreNpniweCVtnRvV4qt0Inm8cXtPyG38BCo/shIWUSvl3WXBmRwzjzfGWx56X6BOmVoCUY5Huuj3WHXUUOpa0l2QWceh4i9Wo7uGTzIhfiiXYCC31SGJfaPSdHmk3uu8j+uBl4WT8/zif91/lcUbi+fW1cOtkm6N66yB3zhWGchJmrJpxSEYoGlZbN1L7jv5CuGleX47LPVYy9y4GCkDmi+J9zod+7GV5vm+w6Nz4nIST7sRwOK4uJR1O2EcjRXBHtPvlK9H8d4rYxR+YRwOZxoiZXXIZnVQYs+IPk329Tmsjh+uj6DOoE9UAd2HrIbxnUcca0XLwTP84Ohj6k0Da+MlCG78icArH5hSMXWlUHge1VR4h3a8BdJpSRvylN1XIujpUWploM1Bsb1Jg1IrJQhG17LMfY6IVnSMLVHlnjtepdcjfJe8d/h5pliaWDHqpw/6Vm197JCr138+NePlX80="
language: python
install: "pip install -r requirements.txt"
script: nosetests
after_failure:
  - python ping.py

